package NuGet_MirukenDotNet_MirukenSolutionKotlin.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '2f710b99-d945-4072-b5dd-463fac99b976_CIBuild' (id = 'NuGet_MirukenDotNet_MirukenSolutionKotlin_CIBuild')
accordingly and delete the patch script.
*/
changeBuildType("2f710b99-d945-4072-b5dd-463fac99b976_CIBuild") {
    vcs {
        remove("NuGet_MirukenDotNet_MirukenSolutionKotlin_CodeVCSRoot")
    }

    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                id = "NuGet_MirukenDotNet_MirukenSolutionKotlin_ci_vcsTrigger"
                quietPeriodMode = VcsTrigger.QuietPeriodMode.USE_DEFAULT
                perCheckinTriggering = true
                groupCheckinsByCommitter = true
                enableQueueOptimization = false
            }
        }
        trigger1.apply {
            enabled = false
        }
    }

    expectDisabledSettings("RUNNER_21", "RUNNER_22", "RUNNER_4", "RUNNER_5", "RUNNER_6", "RUNNER_8", "symbol-indexer")
    updateDisabledSettings("JetBrains.AssemblyInfo", "RUNNER_1", "RUNNER_2", "RUNNER_21", "RUNNER_22", "RUNNER_3", "RUNNER_4", "RUNNER_5", "RUNNER_6", "RUNNER_8", "symbol-indexer")
}
