package NuGet_MirukenDotNet_MirukenSolutionKotlin.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = '6be31c03-f268-4dd9-a2d9-5e553e637b94' (id = 'NuGet_MirukenDotNet_MirukenSolutionKotlin_Foo')
in the project with uuid = '2f710b99-d945-4072-b5dd-463fac99b976' and delete the patch script.
*/
create("2f710b99-d945-4072-b5dd-463fac99b976", GitVcsRoot({
    uuid = "6be31c03-f268-4dd9-a2d9-5e553e637b94"
    id = "NuGet_MirukenDotNet_MirukenSolutionKotlin_Foo"
    name = "foo"
    url = "https://github.com/Miruken-DotNet/Miruken.git"
}))

