package NuGet_MirukenDotNet_MirukenSolutionKotlin.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '2f710b99-d945-4072-b5dd-463fac99b976' (id = 'NuGet_MirukenDotNet_MirukenSolutionKotlin')
accordingly and delete the patch script.
*/
changeProject("2f710b99-d945-4072-b5dd-463fac99b976") {
    check(name == "Miruken Solution Kotlin") {
        "Unexpected name: '$name'"
    }
    name = "Kotlin"
}
