package NuGet_MirukenDotNet_MirukenSolutionKotlin.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '2f710b99-d945-4072-b5dd-463fac99b976_DeploymentProject' (id = 'NuGet_MirukenDotNet_MirukenSolutionKotlin_DeploymentProject')
accordingly and delete the patch script.
*/
changeProject("2f710b99-d945-4072-b5dd-463fac99b976_DeploymentProject") {
    check(subProjectsOrder == arrayListOf("NuGet_MirukenDotNet_MirukenSolutionKotlin_Deployment_Miruken", "NuGet_MirukenDotNet_MirukenSolutionKotlin_Deployment_MirukenCastle", "NuGet_MirukenDotNet_MirukenSolutionKotlin_Deployment_MirukenValidate", "NuGet_MirukenDotNet_MirukenSolutionKotlin_Deployment_MirukenValidateCastle")) {
        "Unexpected subProjectsOrder: '$subProjectsOrder'"
    }
    subProjectsOrder = arrayListOf<String>()
}
