package NuGet_MirukenDotNet_MirukenSolutionKotlin.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = 'f44b63cb-e064-43e6-8a09-cb9788340867' (id = 'NuGet_MirukenDotNet_MirukenSolutionKotlin_MirukenSolution')
in the project with uuid = '2f710b99-d945-4072-b5dd-463fac99b976' and delete the patch script.
*/
create("2f710b99-d945-4072-b5dd-463fac99b976", Project({
    uuid = "f44b63cb-e064-43e6-8a09-cb9788340867"
    id = "NuGet_MirukenDotNet_MirukenSolutionKotlin_MirukenSolution"
    parentId = "NuGet_MirukenDotNet_MirukenSolutionKotlin"
    name = "Miruken Solution"
}))

